"""Public menu UI strings. FR is the reference."""

STRINGS = {
    "fr": {
        "skip": "Aller à la carte",
        "categories": "Catégories",
        "language": "Langue",
        "sold_out": "Épuisé",
        "allergens": "Allergènes",
        "diets": "Régimes",
        "today": "Aujourd'hui",
        "call": "Appeler",
        "directions": "Itinéraire",
        "hours": "Horaires",
        "filter": "Filtrer",
        "filter_title": "Rechercher et filtrer",
        "search": "Rechercher un plat",
        "hide_containing": "Masquer les plats contenant",
        "diet_only": "Afficher uniquement",
        "filter_note": "Indication fournie par le restaurant. En cas d'allergie, demandez au personnel.",
        "show_n": "Voir {n} plats",
        "show_1": "Voir 1 plat",
        "hidden_n": "{n} plats masqués",
        "hidden_1": "1 plat masqué",
        "reset": "Réinitialiser",
        "no_results": "Aucun plat ne correspond.",
        "close": "Fermer",
        "legend_title": "Allergènes et régimes",
        "dish_detail": "Détail du plat",
        "photo_of": "Photo :",
    },
    "en": {
        "skip": "Skip to the menu",
        "categories": "Categories",
        "language": "Language",
        "sold_out": "Sold out",
        "allergens": "Allergens",
        "diets": "Diets",
        "today": "Today",
        "call": "Call",
        "directions": "Directions",
        "hours": "Opening hours",
        "filter": "Filter",
        "filter_title": "Search and filter",
        "search": "Find a dish",
        "hide_containing": "Hide dishes containing",
        "diet_only": "Show only",
        "filter_note": "Information provided by the restaurant. If you have an allergy, please ask the staff.",
        "show_n": "Show {n} dishes",
        "show_1": "Show 1 dish",
        "hidden_n": "{n} dishes hidden",
        "hidden_1": "1 dish hidden",
        "reset": "Reset",
        "no_results": "No dish matches.",
        "close": "Close",
        "legend_title": "Allergens and diets",
        "dish_detail": "Dish details",
        "photo_of": "Photo:",
    },
}


def strings_for(lang: str) -> dict[str, str]:
    return STRINGS.get(lang, STRINGS["fr"])
