# Generated by Django 5.2.17 on 2026-08-25 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import menus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=menus.models.tr_default)),
                ('description', models.JSONField(blank=True, default=menus.models.tr_default)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('tagline', models.JSONField(blank=True, default=menus.models.tr_default)),
                ('logo', models.ImageField(blank=True, upload_to=menus.models.upload_logo_to)),
                ('brand_color', models.CharField(default='#7a2e2a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a hex colour like #7a2e2a.')])),
                ('accent_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a hex colour like #7a2e2a.')])),
                ('theme', models.CharField(choices=[('bistro', 'Bistro'), ('trattoria', 'Trattoria'), ('cafe', 'Café'), ('gastro', 'Gastronomique'), ('auberge', 'Auberge')], default='bistro', max_length=20)),
                ('color_mode', models.CharField(choices=[('auto', 'Follow phone setting'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('maps_url', models.URLField(blank=True, help_text='Optional; defaults to a map search for the address.')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('hours', models.JSONField(blank=True, default=menus.models.tr_default, help_text='Multi-line text per language.')),
                ('footer_note', models.JSONField(blank=True, default=menus.models.tr_default)),
                ('languages', models.JSONField(default=menus.models.default_languages)),
                ('is_published', models.BooleanField(default=False)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Content version; bumped on any change.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=menus.models.tr_default)),
                ('description', models.JSONField(blank=True, default=menus.models.tr_default)),
                ('prices', models.JSONField(blank=True, default=list, validators=[menus.models.validate_prices])),
                ('photo', models.ImageField(blank=True, upload_to=menus.models.upload_photo_to)),
                ('allergens', models.JSONField(blank=True, default=list, validators=[menus.models.validate_allergens])),
                ('diets', models.JSONField(blank=True, default=list, validators=[menus.models.validate_diets])),
                ('is_sold_out', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.category')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('plat', 'Plat du jour'), ('formule', 'Formule du jour'), ('dessert', 'Dessert du jour'), ('suggestion', 'Suggestion du chef')], default='plat', max_length=20)),
                ('title', models.JSONField(default=menus.models.tr_default)),
                ('description', models.JSONField(blank=True, default=menus.models.tr_default)),
                ('prices', models.JSONField(blank=True, default=list, validators=[menus.models.validate_prices])),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='menus.restaurant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menus.restaurant'),
        ),
    ]
